
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * StudentRecordsForm
 */
public class StudentRecordsForm extends javax.swing.JFrame {
    
    // students
    Students students = new Students();
    
    // courses
    Courses courses = new Courses();
    
    // current index, displays what index the search was found in
    int currentIndex = 0;

    /**
     * Creates new form StudentRecordsForm
     */
    public StudentRecordsForm() {
        
      
        initComponents();
        
        // startup
        jButtonSave.setEnabled(false);
        uneditStudents();
        
        // show first student
        if(students.getNumStudents()>0)
            showStudentData(students.getStudent(currentIndex));
        
        // show courses
        if(courses.getNumCourses()>0)
            populateCoursesCombo();
          
        setSize(900,500);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldStreet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPostal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNumber = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldGrade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldProv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldDOB = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldGender = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonStudents = new javax.swing.JButton();
        jButtonCourse = new javax.swing.JButton();
        jComboBoxCourses = new javax.swing.JComboBox();
        jButtonGrades = new javax.swing.JButton();
        jButtonFindSurname = new javax.swing.JButton();
        jTextFieldFindSurname = new javax.swing.JTextField();
        jButtonMark = new javax.swing.JButton();
        jButtonFindNumber = new javax.swing.JButton();
        jTextFieldFindNumber = new javax.swing.JTextField();
        jButtonAge = new javax.swing.JButton();
        jCheckBoxSelectGrade = new javax.swing.JCheckBox();
        jSpinnerGrade = new javax.swing.JSpinner();
        jTextFieldCourseGrade = new javax.swing.JTextField();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jButtonAddCourse = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDisplay = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldCourse7 = new javax.swing.JTextField();
        jTextFieldCourse2 = new javax.swing.JTextField();
        jTextFieldCourse3 = new javax.swing.JTextField();
        jTextFieldCourse5 = new javax.swing.JTextField();
        jTextFieldMark8 = new javax.swing.JTextField();
        jTextFieldMark2 = new javax.swing.JTextField();
        jTextFieldMark6 = new javax.swing.JTextField();
        jTextFieldMark5 = new javax.swing.JTextField();
        jTextFieldCourse4 = new javax.swing.JTextField();
        jTextFieldCourse6 = new javax.swing.JTextField();
        jTextFieldCourse8 = new javax.swing.JTextField();
        jTextFieldCourse1 = new javax.swing.JTextField();
        jTextFieldMark1 = new javax.swing.JTextField();
        jTextFieldMark4 = new javax.swing.JTextField();
        jTextFieldMark3 = new javax.swing.JTextField();
        jTextFieldMark7 = new javax.swing.JTextField();
        jButtonAddCourse2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAverage = new javax.swing.JTextField();
        jComboBoxCourses2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("High School Student Record Application");
        setSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Info"));
        jPanel1.setLayout(null);

        jLabel2.setText("Grade");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 180, 40, 30);

        jTextFieldPhone.setText(" ");
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(340, 140, 80, 30);

        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 30, 80, 20);

        jTextFieldLastName.setText(" ");
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldLastName);
        jTextFieldLastName.setBounds(320, 20, 100, 30);

        jLabel4.setText("Street Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 70, 110, 20);

        jTextFieldStreet.setText(" ");
        jPanel1.add(jTextFieldStreet);
        jTextFieldStreet.setBounds(140, 60, 280, 30);

        jLabel5.setText("Postal Code");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 100, 70, 30);

        jTextFieldPostal.setText(" ");
        jPanel1.add(jTextFieldPostal);
        jTextFieldPostal.setBounds(360, 100, 60, 30);

        jLabel6.setText("City");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 100, 40, 30);

        jTextFieldNumber.setText(" ");
        jTextFieldNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumberActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNumber);
        jTextFieldNumber.setBounds(230, 180, 90, 30);

        jTextFieldFirstName.setText(" ");
        jPanel1.add(jTextFieldFirstName);
        jTextFieldFirstName.setBounds(110, 20, 100, 30);

        jLabel8.setText("First Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 30, 70, 20);

        jTextFieldGrade.setText(" ");
        jPanel1.add(jTextFieldGrade);
        jTextFieldGrade.setBounds(390, 180, 30, 30);

        jLabel9.setText("Date of Birth");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 140, 80, 20);

        jTextFieldProv.setText(" ");
        jPanel1.add(jTextFieldProv);
        jTextFieldProv.setBounds(230, 100, 40, 30);

        jLabel10.setText("Student Number");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(140, 180, 100, 30);

        jTextFieldCity.setText(" ");
        jPanel1.add(jTextFieldCity);
        jTextFieldCity.setBounds(70, 100, 90, 30);

        jLabel11.setText("Home Phone");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 140, 80, 30);

        jLabel12.setText("Age");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(190, 140, 30, 30);

        jTextFieldAge.setText(" ");
        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAge);
        jTextFieldAge.setBounds(220, 140, 40, 30);

        jLabel15.setText("Province");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(180, 100, 60, 30);

        jTextFieldDOB.setText(" ");
        jTextFieldDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDOBActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDOB);
        jTextFieldDOB.setBounds(100, 140, 80, 30);

        jLabel16.setText("Gender");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 180, 50, 30);

        jTextFieldGender.setText(" ");
        jTextFieldGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGenderActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldGender);
        jTextFieldGender.setBounds(80, 180, 30, 30);

        jLabel17.setText("mm/dd/yyyy");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 150, 80, 20);

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNext);
        jButtonNext.setBounds(220, 220, 129, 25);

        jButtonPrevious.setText("Previous");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrevious);
        jButtonPrevious.setBounds(80, 220, 129, 25);

        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNew);
        jButtonNew.setBounds(10, 260, 132, 25);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit);
        jButtonEdit.setBounds(150, 260, 132, 25);

        jButtonSave.setText("Add");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave);
        jButtonSave.setBounds(290, 260, 132, 25);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));
        jPanel5.setLayout(new java.awt.GridLayout(7, 3));

        jButtonStudents.setText("List Students");
        jButtonStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentsActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonStudents);

        jButtonCourse.setText("List by Course");
        jButtonCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCourseActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonCourse);

        jComboBoxCourses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Course", " " }));
        jComboBoxCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCoursesActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBoxCourses);

        jButtonGrades.setText("List by Grades");
        jButtonGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGradesActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonGrades);

        jButtonFindSurname.setText("Find by Surname");
        jButtonFindSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindSurnameActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonFindSurname);

        jTextFieldFindSurname.setText(" ");
        jPanel5.add(jTextFieldFindSurname);

        jButtonMark.setText("List by Mark");
        jButtonMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarkActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonMark);

        jButtonFindNumber.setText("Find by Number");
        jButtonFindNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindNumberActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonFindNumber);

        jTextFieldFindNumber.setText(" ");
        jPanel5.add(jTextFieldFindNumber);

        jButtonAge.setText("List by Age");
        jButtonAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgeActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAge);

        jCheckBoxSelectGrade.setText("Select Grade");
        jPanel5.add(jCheckBoxSelectGrade);

        jSpinnerGrade.setModel(new javax.swing.SpinnerNumberModel(9, 9, 12, 1));
        jPanel5.add(jSpinnerGrade);

        jTextFieldCourseGrade.setText("Course Grade");
        jPanel5.add(jTextFieldCourseGrade);

        jTextFieldCode.setText("Course Code");
        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldCode);

        jTextFieldDescription.setText("Course Description");
        jPanel5.add(jTextFieldDescription);

        jButtonAddCourse.setText("Add Course");
        jButtonAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCourseActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAddCourse);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 290, 400, 200);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 430, 500);

        jTextField9.setText("jTextField1");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(100, 100, 59, 20);

        jTextField10.setText("jTextField1");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(100, 100, 59, 20);

        jLabel13.setText("First Name");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 130, 51, 14);

        jLabel14.setText("First Name");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(27, 68, 51, 20);

        jTextAreaDisplay.setColumns(20);
        jTextAreaDisplay.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        jTextAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDisplay);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 250, 410, 250);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Courses and Marks"));
        jPanel3.setLayout(null);

        jTextFieldCourse7.setText(" ");
        jPanel3.add(jTextFieldCourse7);
        jTextFieldCourse7.setBounds(10, 140, 130, 30);

        jTextFieldCourse2.setText(" ");
        jPanel3.add(jTextFieldCourse2);
        jTextFieldCourse2.setBounds(230, 20, 130, 30);

        jTextFieldCourse3.setText(" ");
        jPanel3.add(jTextFieldCourse3);
        jTextFieldCourse3.setBounds(10, 60, 130, 30);

        jTextFieldCourse5.setText(" ");
        jPanel3.add(jTextFieldCourse5);
        jTextFieldCourse5.setBounds(10, 100, 130, 30);

        jTextFieldMark8.setText(" ");
        jPanel3.add(jTextFieldMark8);
        jTextFieldMark8.setBounds(380, 140, 40, 30);

        jTextFieldMark2.setText(" ");
        jPanel3.add(jTextFieldMark2);
        jTextFieldMark2.setBounds(380, 20, 40, 30);

        jTextFieldMark6.setText(" ");
        jPanel3.add(jTextFieldMark6);
        jTextFieldMark6.setBounds(380, 100, 40, 30);

        jTextFieldMark5.setText(" ");
        jPanel3.add(jTextFieldMark5);
        jTextFieldMark5.setBounds(160, 100, 40, 30);

        jTextFieldCourse4.setText(" ");
        jPanel3.add(jTextFieldCourse4);
        jTextFieldCourse4.setBounds(230, 60, 130, 30);

        jTextFieldCourse6.setText(" ");
        jPanel3.add(jTextFieldCourse6);
        jTextFieldCourse6.setBounds(230, 100, 130, 30);

        jTextFieldCourse8.setText(" ");
        jPanel3.add(jTextFieldCourse8);
        jTextFieldCourse8.setBounds(230, 140, 130, 30);

        jTextFieldCourse1.setText(" ");
        jPanel3.add(jTextFieldCourse1);
        jTextFieldCourse1.setBounds(10, 20, 130, 30);

        jTextFieldMark1.setText(" ");
        jPanel3.add(jTextFieldMark1);
        jTextFieldMark1.setBounds(160, 20, 40, 30);

        jTextFieldMark4.setText(" ");
        jPanel3.add(jTextFieldMark4);
        jTextFieldMark4.setBounds(380, 60, 40, 30);

        jTextFieldMark3.setText(" ");
        jPanel3.add(jTextFieldMark3);
        jTextFieldMark3.setBounds(160, 60, 40, 30);

        jTextFieldMark7.setText(" ");
        jPanel3.add(jTextFieldMark7);
        jTextFieldMark7.setBounds(160, 140, 40, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(450, 10, 430, 180);

        jButtonAddCourse2.setText("Add Course");
        jButtonAddCourse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCourse2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddCourse2);
        jButtonAddCourse2.setBounds(620, 200, 110, 30);

        jLabel7.setText("Average");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(760, 200, 50, 30);
        getContentPane().add(jTextFieldAverage);
        jTextFieldAverage.setBounds(810, 200, 60, 30);

        jComboBoxCourses2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Course", " " }));
        getContentPane().add(jComboBoxCourses2);
        jComboBoxCourses2.setBounds(460, 200, 120, 30);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(640, 300, 210, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        
        // this button makes the student record display the info for the next student
        if(currentIndex < students.getNumStudents()-1)
        {
            currentIndex++;
            showStudentData(students.getStudent(currentIndex));
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        //add new student
        
        clearStudents();
        editStudents();
        
        jButtonSave.setText("Add");
        jButtonSave.setEnabled(true);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
      //edit a student record
        editStudents();
       jButtonSave.setText("Save");
       jButtonSave.setEnabled(true);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        //add a new student record
       
      Student s = getStudentData();
      
      if(s != null)
      {
       uneditStudents();
       jButtonSave.setEnabled(false);
       
       // Add a new student record
       if(jButtonSave.getText().equals("Add"))
       {
           students.addStudent(s);
           showStudentData(s);
           
       }
       
       //Save a student record
       else if(jButtonSave.getText().equals("Save"))
       {
           students.updateStudent(currentIndex,s);
           showStudentData(s);
       }
      }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
              // previous student
        if(students.getNumStudents()>0 && currentIndex > 0)
        {
            currentIndex--;
            showStudentData(students.getStudent(currentIndex));
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonAddCourse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCourse2ActionPerformed
        //add course button but in actual course selection box
        if(jButtonSave.isEnabled())
        {
        // get code
        String code = jComboBoxCourses2.getSelectedItem().toString();
        
        // find empty slot
        if(jTextFieldCourse1.getText().trim().equals(""))
        {
            jTextFieldCourse1.setText(code);
            return;
        }
        //.TRIM GETS RID OF WHITESPACE
        if(jTextFieldCourse2.getText().trim().equals(""))
        {
            jTextFieldCourse2.setText(code);
            return;
        }
        if(jTextFieldCourse3.getText().trim().equals(""))
        {
            jTextFieldCourse3.setText(code);
            return;
        }
        if(jTextFieldCourse4.getText().trim().equals(""))
        {
            jTextFieldCourse4.setText(code);
            return;
        }
        if(jTextFieldCourse5.getText().trim().equals(""))
        {
            jTextFieldCourse5.setText(code);
            return;
        }
        if(jTextFieldCourse6.getText().trim().equals(""))
        {
            jTextFieldCourse6.setText(code);
            return;
        }
        if(jTextFieldCourse7.getText().trim().equals(""))
        {
            jTextFieldCourse7.setText(code);
            return;
        }
        if(jTextFieldCourse8.getText().trim().equals(""))
        {
            jTextFieldCourse8.setText(code);
            return;
        }
        
        }
        
    }//GEN-LAST:event_jButtonAddCourse2ActionPerformed

    private void jTextFieldDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOBActionPerformed

    private void jTextFieldNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumberActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGenderActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jButtonStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentsActionPerformed

        ArrayList<Student> list = students.sortAlphabetically();

        jTextAreaDisplay.setText(""); // clear test

        for(Student s:list)
        {
            jTextAreaDisplay.append(String.format("%-10s %-40s %2s %4d %4d %8.1f %10s\n",
                s.getStudentNumber(),s.getFirstName() + " " + s.getLastName(),
                s.getGender(),s.getAge(),s.getGrade(),s.getAverage(),s.getHomePhoneNumber()));
        }

    }//GEN-LAST:event_jButtonStudentsActionPerformed

    private void jButtonFindSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindSurnameActionPerformed

        // get surname
        String surname = jTextFieldFindSurname.getText().trim();
        int index = students.findStudentSurname(surname);
        if(index>= 0)
        {
            currentIndex = index;
            showStudentData(students.getStudent(currentIndex));
            jTextAreaDisplay.setText("Surname " + surname + " found at student record " + index);
        }

        else
        {
            jTextAreaDisplay.setText("Surname " + surname + " not found");
        }
    }//GEN-LAST:event_jButtonFindSurnameActionPerformed

    private void jButtonGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGradesActionPerformed

        ArrayList<Student> list = students.sortAlphabeticallyByGrade();

        jTextAreaDisplay.setText(""); // clear test

        for(Student s:list)
        {
            jTextAreaDisplay.append(String.format("%-10s %-40s %2s %4d %4d %8.1f %10s\n",
                s.getStudentNumber(),s.getFirstName() + " " + s.getLastName(),
                s.getGender(),s.getAge(),s.getGrade(),s.getAverage(),s.getHomePhoneNumber()));
        }
    }//GEN-LAST:event_jButtonGradesActionPerformed

    private void jButtonFindNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindNumberActionPerformed

        // get number
        String number = jTextFieldFindNumber.getText().trim();
        int index = students.findStudentNumber(number);
        if(index>= 0)
        {
            currentIndex = index;
            showStudentData(students.getStudent(currentIndex));
            jTextAreaDisplay.setText("Student Number " + number + " found at index " + index);
        }

        else
        {
            jTextAreaDisplay.setText("Student Number " + number + " not found");
        }
    }//GEN-LAST:event_jButtonFindNumberActionPerformed

    private void jButtonAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgeActionPerformed

        ArrayList<Student> list = students.sortByAge();

        jTextAreaDisplay.setText(""); // clear test

        for(Student s:list)
        {
            jTextAreaDisplay.append(String.format("%-10s %-40s %2s %4d %4d %8.1f %10s\n",
                s.getStudentNumber(),s.getFirstName() + " " + s.getLastName(),
                s.getGender(),s.getAge(),s.getGrade(),s.getAverage(),s.getHomePhoneNumber()));
        }

    }//GEN-LAST:event_jButtonAgeActionPerformed

    private void jButtonCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCourseActionPerformed

        ArrayList<Student> list=null;

        // get course code
        String code = jComboBoxCourses.getSelectedItem().toString();

        if(jCheckBoxSelectGrade.isSelected())
        {
            int grade = Integer.parseInt(jSpinnerGrade.getValue().toString());
            list = students.sortByCourseGrade(code, grade);
        }
        else
        {
            list = students.sortByCourse(code);
        }

        jTextAreaDisplay.setText(""); // clear test

        for(Student s:list)
        {
            jTextAreaDisplay.append(String.format("%-10s %-40s %2s %4d %4d %8.1f %10s\n",
                s.getStudentNumber(),s.getFirstName() + " " + s.getLastName(),
                s.getGender(),s.getAge(),s.getGrade(),s.getAverage(),s.getHomePhoneNumber()));
        }
    }//GEN-LAST:event_jButtonCourseActionPerformed

    private void jComboBoxCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCoursesActionPerformed

        if(jComboBoxCourses.getSelectedItem()!=null)
        {
            // get code
            String code = jComboBoxCourses.getSelectedItem().toString();

            Course c = courses.findCourse(code);

            if(c != null)
            {
                // set course data
                jTextFieldCode.setText(c.getCourseCode());
                jTextFieldCourseGrade.setText(String.valueOf(c.getGrade()));
                jTextFieldDescription.setText(c.getCourseDescription());
            }
        }
    }//GEN-LAST:event_jComboBoxCoursesActionPerformed

    private void jButtonAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCourseActionPerformed

        try
        {
            // get course data
            String code = jTextFieldCode.getText();
            String grade = jTextFieldCourseGrade.getText();
            String description = jTextFieldDescription.getText();

            // make course
            Course c = new Course(code, Integer.parseInt(grade),description);

            // add course
            courses.addCourse(c);

            // populate combo
            populateCoursesCombo();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }

    }//GEN-LAST:event_jButtonAddCourseActionPerformed

    private void jButtonMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarkActionPerformed

        ArrayList<Student> list=null;

        if(jCheckBoxSelectGrade.isSelected())
        {
            int grade = Integer.parseInt(jSpinnerGrade.getValue().toString());
            list = students.sortByGrade(grade);
        }
        else
        {
            list = students.sortByGrade();
        }

        jTextAreaDisplay.setText(""); // clear test

        for(Student s:list)
        {
            jTextAreaDisplay.append(String.format("%-10s %-40s %2s %4d %4d %8.1f %10s\n",
                s.getStudentNumber(),s.getFirstName() + " " + s.getLastName(),
                s.getGender(),s.getAge(),s.getGrade(),s.getAverage(),s.getHomePhoneNumber()));
        }
    }//GEN-LAST:event_jButtonMarkActionPerformed

    private void jTextFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeActionPerformed

    // populate courses combo box
    public void populateCoursesCombo()
    {
        jComboBoxCourses.removeAllItems();
        jComboBoxCourses2.removeAllItems();
        
        for(int i=0;i<courses.getNumCourses();i++)
        {
            jComboBoxCourses.addItem(courses.getCourse(i).getCourseCode());
            jComboBoxCourses2.addItem(courses.getCourse(i).getCourseCode());
        }
    }
    
    // clear student textbox
    private void clearStudents()
    {
        // student info
    jTextFieldFirstName.setText("");
    jTextFieldLastName.setText("");
    jTextFieldStreet.setText("");
    jTextFieldCity.setText("");
    jTextFieldProv.setText("");
    jTextFieldPostal.setText("");
    jTextFieldNumber.setText("");
    jTextFieldPhone.setText("");
    jTextFieldDOB.setText(""); 
    jTextFieldGender.setText("");
    jTextFieldAge.setText("");
    jTextFieldGrade.setText("");
    jTextFieldAverage.setText("");
    
    // courses
     jTextFieldCourse1.setText("");
     jTextFieldCourse2.setText("");
     jTextFieldCourse3.setText("");
     jTextFieldCourse4.setText("");
     jTextFieldCourse5.setText("");
     jTextFieldCourse6.setText("");
     jTextFieldCourse7.setText("");
     jTextFieldCourse8.setText("");
    
    // marks
     jTextFieldMark1.setText("0");
     jTextFieldMark2.setText("0");
     jTextFieldMark3.setText("0");
     jTextFieldMark4.setText("0");
     jTextFieldMark5.setText("0");
     jTextFieldMark6.setText("0");
     jTextFieldMark7.setText("0");
     jTextFieldMark8.setText("0");
    }
    
     
    private void editStudents()
    {
        // edit student record
    jTextFieldFirstName.setEditable(true);
    jTextFieldLastName.setEditable(true);
    jTextFieldStreet.setEditable(true);
    jTextFieldCity.setEditable(true);
    jTextFieldProv.setEditable(true);
    jTextFieldPostal.setEditable(true);
    jTextFieldNumber.setEditable(true);
    jTextFieldPhone.setEditable(true);
    jTextFieldDOB.setEditable(true); 
    jTextFieldGender.setEditable(true);
    //age is calculated
    //jTextFieldAge.setEditable(true);
    jTextFieldGrade.setEditable(true);
    //average is calculated
    //jTextFieldAverage.setEditable(true);
    
    // courses
     jTextFieldCourse1.setEditable(true);
     jTextFieldCourse2.setEditable(true);
     jTextFieldCourse3.setEditable(true);
     jTextFieldCourse4.setEditable(true);
     jTextFieldCourse5.setEditable(true);
     jTextFieldCourse6.setEditable(true);
     jTextFieldCourse7.setEditable(true);
     jTextFieldCourse8.setEditable(true);
    
    // marks
     jTextFieldMark1.setEditable(true);
     jTextFieldMark2.setEditable(true);
     jTextFieldMark3.setEditable(true);
     jTextFieldMark4.setEditable(true);
     jTextFieldMark5.setEditable(true);
     jTextFieldMark6.setEditable(true);
     jTextFieldMark7.setEditable(true);
     jTextFieldMark8.setEditable(true);   
    }
    
    
    private void uneditStudents()
    {
        // student info
       // unedit student textbox

    jTextFieldFirstName.setEditable(false);
    jTextFieldLastName.setEditable(false);
    jTextFieldStreet.setEditable(false);
    jTextFieldCity.setEditable(false);
    jTextFieldProv.setEditable(false);
    jTextFieldPostal.setEditable(false);
    jTextFieldNumber.setEditable(false);
    jTextFieldPhone.setEditable(false);
    jTextFieldDOB.setEditable(false); 
    jTextFieldGender.setEditable(false);
    jTextFieldAge.setEditable(false);
    jTextFieldGrade.setEditable(false);
    jTextFieldAverage.setEditable(false);
    
    // courses
     jTextFieldCourse1.setEditable(false);
     jTextFieldCourse2.setEditable(false);
     jTextFieldCourse3.setEditable(false);
     jTextFieldCourse4.setEditable(false);
     jTextFieldCourse5.setEditable(false);
     jTextFieldCourse6.setEditable(false);
     jTextFieldCourse7.setEditable(false);
     jTextFieldCourse8.setEditable(false);
    
    // marks
     jTextFieldMark1.setEditable(false);
     jTextFieldMark2.setEditable(false);
     jTextFieldMark3.setEditable(false);
     jTextFieldMark4.setEditable(false);
     jTextFieldMark5.setEditable(false);
     jTextFieldMark6.setEditable(false);
     jTextFieldMark7.setEditable(false);
     jTextFieldMark8.setEditable(false);   
    }
    
    
      // get Student data
    private Student getStudentData()
    {
        // student info
        Student s = new Student();
    try
    {
    s.setFirstName(jTextFieldFirstName.getText().trim());
    s.setLastName(jTextFieldLastName.getText().trim());
    s.setStreetAddress(jTextFieldStreet.getText().trim());
    s.setCity(jTextFieldCity.getText().trim());
    s.setProvince(jTextFieldProv.getText().trim());
    s.setPostalCode(jTextFieldPostal.getText().trim());
    s.setStudentNumber(jTextFieldNumber.getText().trim());
    s.setHomePhoneNumber(jTextFieldPhone.getText().trim());
    s.setDateofBirth(jTextFieldDOB.getText().trim()); 
    s.setGender(jTextFieldGender.getText().trim());
    //jTextFieldAge.getText());
    s.setGrade(Integer.parseInt(jTextFieldGrade.getText().trim()));
    //jTextFieldAverage
    
    // calculate average
    s.calculateAge();
    
    // courses
     s.setCourse(0, jTextFieldCourse1.getText().trim());
     s.setCourse(1, jTextFieldCourse2.getText().trim());
     s.setCourse(2, jTextFieldCourse3.getText().trim());
     s.setCourse(3, jTextFieldCourse4.getText().trim());
     s.setCourse(4, jTextFieldCourse5.getText().trim());
     s.setCourse(5, jTextFieldCourse6.getText().trim());
     s.setCourse(6, jTextFieldCourse7.getText().trim());
     s.setCourse(7, jTextFieldCourse8.getText().trim());
    
    // marks
     s.setMark(0, Double.parseDouble(jTextFieldMark1.getText().trim()));
     s.setMark(1, Double.parseDouble(jTextFieldMark2.getText().trim()));
     s.setMark(2, Double.parseDouble(jTextFieldMark3.getText().trim()));
     s.setMark(3, Double.parseDouble(jTextFieldMark4.getText().trim()));
     s.setMark(4, Double.parseDouble(jTextFieldMark5.getText().trim()));
     s.setMark(5, Double.parseDouble(jTextFieldMark6.getText().trim()));
     s.setMark(6, Double.parseDouble(jTextFieldMark7.getText().trim()));
     s.setMark(7, Double.parseDouble(jTextFieldMark8.getText().trim()));
     
     s.calculateAverage();
     
      return s;
    }
    catch(Exception ex)
    {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        return null;
    }
    
   
    }
    
    
    private void showStudentData(Student s)
    {
    // display Student data

    jTextFieldFirstName.setText(s.getFirstName());
    jTextFieldLastName.setText(s.getLastName());
    jTextFieldStreet.setText(s.getStreetAddress());
    jTextFieldCity.setText(s.getCity());
    jTextFieldProv.setText(s.getProvince());
    jTextFieldPostal.setText(s.getPostalCode());
    jTextFieldNumber.setText(s.getStudentNumber());
    jTextFieldPhone.setText(s.getHomePhoneNumber());
    jTextFieldDOB.setText(s.getDateofBirth()); 
    jTextFieldGender.setText(s.getGender());
    jTextFieldAge.setText(String.valueOf(s.getAge()));
    jTextFieldGrade.setText(String.valueOf(s.getGrade()));
    jTextFieldAverage.setText(String.format("%.1f",s.getAverage()));
    
    // courses
     jTextFieldCourse1.setText(s.getCourse(0));
     jTextFieldCourse2.setText(s.getCourse(1));
     jTextFieldCourse3.setText(s.getCourse(2));
     jTextFieldCourse4.setText(s.getCourse(3));
     jTextFieldCourse5.setText(s.getCourse(4));
     jTextFieldCourse6.setText(s.getCourse(5));
     jTextFieldCourse7.setText(s.getCourse(6));
     jTextFieldCourse8.setText(s.getCourse(7));
    
    // marks
    //%f=decimal number
     jTextFieldMark1.setText(String.format("%.1f", s.getMark(0)));
     jTextFieldMark2.setText(String.format("%.1f", s.getMark(1)));
     jTextFieldMark3.setText(String.format("%.1f", s.getMark(2)));
     jTextFieldMark4.setText(String.format("%.1f", s.getMark(3)));
     jTextFieldMark5.setText(String.format("%.1f", s.getMark(4)));
     jTextFieldMark6.setText(String.format("%.1f", s.getMark(5)));
     jTextFieldMark7.setText(String.format("%.1f", s.getMark(6)));
     jTextFieldMark8.setText(String.format("%.1f", s.getMark(7)));
 
    }
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecordsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecordsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecordsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecordsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecordsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCourse;
    private javax.swing.JButton jButtonAddCourse2;
    private javax.swing.JButton jButtonAge;
    private javax.swing.JButton jButtonCourse;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonFindNumber;
    private javax.swing.JButton jButtonFindSurname;
    private javax.swing.JButton jButtonGrades;
    private javax.swing.JButton jButtonMark;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonStudents;
    private javax.swing.JCheckBox jCheckBoxSelectGrade;
    private javax.swing.JComboBox jComboBoxCourses;
    private javax.swing.JComboBox jComboBoxCourses2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerGrade;
    private javax.swing.JTextArea jTextAreaDisplay;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldAverage;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldCourse1;
    private javax.swing.JTextField jTextFieldCourse2;
    private javax.swing.JTextField jTextFieldCourse3;
    private javax.swing.JTextField jTextFieldCourse4;
    private javax.swing.JTextField jTextFieldCourse5;
    private javax.swing.JTextField jTextFieldCourse6;
    private javax.swing.JTextField jTextFieldCourse7;
    private javax.swing.JTextField jTextFieldCourse8;
    private javax.swing.JTextField jTextFieldCourseGrade;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldFindNumber;
    private javax.swing.JTextField jTextFieldFindSurname;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldGrade;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMark1;
    private javax.swing.JTextField jTextFieldMark2;
    private javax.swing.JTextField jTextFieldMark3;
    private javax.swing.JTextField jTextFieldMark4;
    private javax.swing.JTextField jTextFieldMark5;
    private javax.swing.JTextField jTextFieldMark6;
    private javax.swing.JTextField jTextFieldMark7;
    private javax.swing.JTextField jTextFieldMark8;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldPostal;
    private javax.swing.JTextField jTextFieldProv;
    private javax.swing.JTextField jTextFieldStreet;
    // End of variables declaration//GEN-END:variables
}
